/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StaticLoaderProtocol */

#ifndef _Included_StaticLoaderProtocol
#define _Included_StaticLoaderProtocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StaticLoaderProtocol
 * Method:    GrabCallbackTable
 * Signature: (LStaticLoaderProtocol/CallbackTable;)I
 */
JNIEXPORT jint JNICALL Java_StaticLoaderProtocol_GrabCallbackTable
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
